# Generated by Django 5.1.3 on 2024-11-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Мужчина'), ('FEMALE', 'Женщина')], default='MALE', max_length=20, verbose_name='Пол'),
            preserve_default=False,
        ),
    ]
