# Generated by Django 5.1.3 on 2024-11-18 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='days_of_week',
        ),
        migrations.CreateModel(
            name='StudyGroupDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Понедельник'), (2, 'Вторник'), (3, 'Среда'), (4, 'Четверг'), (5, 'Пятница'), (6, 'Суббота'), (7, 'Воскресенье')], verbose_name='День недели')),
                ('start_time', models.TimeField(verbose_name='Время начала занятия')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_days', to='students.studygroup', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'День занятий',
                'verbose_name_plural': 'Дни занятий',
                'ordering': ['day_of_week'],
                'unique_together': {('group', 'day_of_week')},
            },
        ),
    ]
