# Generated by Django 5.1.3 on 2024-11-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studygroup_days_of_week_studygroupday'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='lesson_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена за занятие'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StudentVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_visits', to='students.studylesson', verbose_name='Занятие')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_visits', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Посещение занятия',
                'verbose_name_plural': 'Посещения занятий',
                'ordering': ['id'],
            },
        ),
    ]
