# Generated by Django 5.1.3 on 2024-11-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_balance_studygroup_lesson_price_studentvisit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='lesson_price',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена'),
        ),
    ]
