# Generated by Django 5.1.3 on 2024-11-23 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_remove_studygroup_lesson_price_studygroup_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('old_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Старый баланс')),
                ('new_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Новый баланс')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Изменение баланса',
                'verbose_name_plural': 'Изменения баланса',
                'ordering': ['-created_at'],
            },
        ),
    ]
