# Generated by Django 5.1.3 on 2024-11-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_studenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/students/avatars/', verbose_name='Аватарка'),
        ),
    ]
