# Generated by Django 5.1.3 on 2024-12-02 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_avatar'),
        ('user', '0003_worker_department_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='department',
            field=models.CharField(choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='user.worker', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='end_date',
            field=models.DateField(verbose_name='Дата конца'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
