# Generated by Django 5.1.3 on 2024-12-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_studentbalanceadjustment_comment_studentbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbonus',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
    ]
