# Generated by Django 5.1.3 on 2024-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_studentbonus_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='account_number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Лицевой счет'),
        ),
    ]
