# Generated by Django 5.1.3 on 2024-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_student_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marked_for_delete',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='studentbalanceadjustment',
            name='marked_for_delete',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='studentbonus',
            name='marked_for_delete',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='marked_for_delete',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
