# Generated by Django 5.1.3 on 2024-12-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_student_marked_for_delete_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
    ]
