# Generated by Django 5.1.3 on 2025-01-07 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_remove_student_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttogroup',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 9, 15, 43, 799812, tzinfo=datetime.timezone.utc), verbose_name='Дата зачисления'),
        ),
    ]
