# Generated by Django 5.1.3 on 2025-01-07 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_studenttogroup_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='studenttogroup',
            name='joined_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 7, 10, 34, 27, 121661, tzinfo=datetime.timezone.utc), verbose_name='Дата зачисления'),
        ),
    ]
