# Generated by Django 5.1.3 on 2025-01-07 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_student_department_alter_studenttogroup_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttogroup',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления'),
        ),
    ]
