# Generated by Django 5.1.3 on 2025-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_studenttogroup_joined_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='parent_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона родителя'),
        ),
    ]
