# Generated by Django 5.1.3 on 2024-11-22 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_student_balance_studygroup_lesson_price_studentvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Перевод')], max_length=50, verbose_name='Метод платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Касса',
                'verbose_name_plural': 'Кассы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutlayCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
            ],
            options={
                'verbose_name': 'Категория прочих расходов',
                'verbose_name_plural': 'Категории прочих расходов',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OutlayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('outlay_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payment.outlaycategory', verbose_name='')),
            ],
            options={
                'verbose_name': 'Прочие расходы',
                'verbose_name_plural': 'Прочие расходы',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('payment_type', models.CharField(choices=[('INCOME', 'Приход'), ('OUTCOME', 'Расход')], max_length=50, verbose_name='Тип оплаты')),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Перевод')], max_length=50, verbose_name='Метод оплаты')),
                ('payment_model_type', models.CharField(choices=[('STUDENT', 'Студент'), ('OUTLAY', 'Прочие расходы')], max_length=50, verbose_name='Тип источника оплаты')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма')),
                ('created_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('deleted_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='Удалил')),
                ('outlay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payment.outlayitem', verbose_name='Прочие расходы')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='students.student', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
