# Generated by Django 5.1.3 on 2024-11-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlayitem',
            old_name='outlay_category',
            new_name='category',
        ),
    ]
