# Generated by Django 5.1.3 on 2024-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_comment_alter_outlayitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Сумма'),
        ),
    ]
