# Generated by Django 5.1.3 on 2024-12-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_cash_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод'), ('TRANSFER', 'Перечисление'), ('HUMO', 'Хумо'), ('UZCARD', 'Узкард'), ('CLICK', 'CLICK'), ('PAYME', 'PAYME'), ('UZUM', 'UZUM')], max_length=50, verbose_name='Метод платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Перевод'), ('TRANSFER', 'Перечисление'), ('HUMO', 'Хумо'), ('UZCARD', 'Узкард'), ('CLICK', 'CLICK'), ('PAYME', 'PAYME'), ('UZUM', 'UZUM')], max_length=50, verbose_name='Метод оплаты'),
        ),
    ]
