# Generated by Django 5.1.3 on 2024-12-06 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paycomuz', '0005_alter_transaction_id'),
        ('payment', '0005_alter_cash_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payme_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='paycomuz.transaction', verbose_name='Payme транзакция'),
        ),
    ]
