# Generated by Django 5.1.3 on 2024-12-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_payment_payme_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='marked_for_delete',
            field=models.BooleanField(default=False, verbose_name='Помечен на удаление'),
        ),
    ]
