# Generated by Django 5.1.3 on 2024-12-13 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_payment_payment_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
    ]
