# Generated by Django 5.1.3 on 2024-12-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlaycategory',
            name='department',
            field=models.CharField(choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, verbose_name='Отдел'),
        ),
    ]
