# Generated by Django 5.1.3 on 2025-01-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_outlaycategory_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='student_balance_after',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Баланс студента после оплаты'),
        ),
    ]
