# Generated by Django 5.1.3 on 2025-03-11 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_payment_student_balance_after'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlayitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='payment.outlaycategory', verbose_name='Категория'),
        ),
    ]
