# Generated by Django 5.1.3 on 2024-12-02 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_options_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='department',
            field=models.CharField(choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('CASHIER', 'Кассир'), ('ACCOUNTANT', 'Бухгалтер'), ('TEACHER', 'Учитель')], default='ADMIN', max_length=100, verbose_name='Роль'),
        ),
    ]
