# Generated by Django 5.1.3 on 2024-12-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_worker_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='department',
            field=models.CharField(blank=True, choices=[('SCHOOL', 'Школа'), ('KINDERGARTEN', 'Детский сад'), ('CAMP', 'Лагерь')], default='SCHOOL', max_length=50, null=True, verbose_name='Отдел'),
        ),
    ]
